version: "3"

services:
  dev-postgres:
    image: postgres
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ${HOME}/iot-postgres-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 90:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
