version: "3"

services:
  app:
    image: iagosrm/poli-iot-cloud
    ports:
      - 3002:3002
    depends_on:
      postgres:
        condition: service_healthy
    command: ["npm", "start"]
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=test
    volumes:
      - ${HOME}/iot-postgres-data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
